// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsVut_JxZw9lpIy3eGp9UZNBC7MgDfae8',
    appId: '1:713299904126:web:9ddab6c4db0f2f4f907a2f',
    messagingSenderId: '713299904126',
    projectId: 'blood-bank-management-sy-54568',
    authDomain: 'blood-bank-management-sy-54568.firebaseapp.com',
    storageBucket: 'blood-bank-management-sy-54568.firebasestorage.app',
    measurementId: 'G-41EBFV0CVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr8UCeXohyX36mR7qz04iHV8Lq8HDsQmk',
    appId: '1:713299904126:android:553b9f54a1dd0041907a2f',
    messagingSenderId: '713299904126',
    projectId: 'blood-bank-management-sy-54568',
    storageBucket: 'blood-bank-management-sy-54568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTIBGbEQCqhxFe2x9pRUkThSeXHsD0Hyc',
    appId: '1:713299904126:ios:588c2b3974df5b14907a2f',
    messagingSenderId: '713299904126',
    projectId: 'blood-bank-management-sy-54568',
    storageBucket: 'blood-bank-management-sy-54568.firebasestorage.app',
    iosBundleId: 'com.bloodbank.bloodBankManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTIBGbEQCqhxFe2x9pRUkThSeXHsD0Hyc',
    appId: '1:713299904126:ios:588c2b3974df5b14907a2f',
    messagingSenderId: '713299904126',
    projectId: 'blood-bank-management-sy-54568',
    storageBucket: 'blood-bank-management-sy-54568.firebasestorage.app',
    iosBundleId: 'com.bloodbank.bloodBankManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsVut_JxZw9lpIy3eGp9UZNBC7MgDfae8',
    appId: '1:713299904126:web:77e310fcf89b6443907a2f',
    messagingSenderId: '713299904126',
    projectId: 'blood-bank-management-sy-54568',
    authDomain: 'blood-bank-management-sy-54568.firebaseapp.com',
    storageBucket: 'blood-bank-management-sy-54568.firebasestorage.app',
    measurementId: 'G-HCHVM723DT',
  );
}
